DROP DATABASE IF EXISTS nextStepResume_db;
CREATE DATABASE nextStepResume_db;

USE nextStepResume_db;

CREATE TABLE user_table (
    id int NOT NULL AUTO_INCREMENT,
    user_password varchar(32),
    user_pin int(8),
    PRIMARY KEY (id)
);

CREATE TABLE user_info (
    id int NOT NULL AUTO_INCREMENT,
    user_name varchar(500),
    user_email varchar(50),
    picture_url varchar(500),
    full_name varchar(50),
    phone_number varchar(15),
    user_address varchar(500),
    linked_in varchar(500),
    github varchar(500),
    opening_statement varchar(500),
    quote varchar(500),
    job1_skills varchar(500),
    job1_start varchar(50),
    job1_end varchar(50),
    job1_title varchar(50),
    job1_description varchar(500),
    job1_company_name varchar(50),
    job2_skills varchar(500),
    job2_start varchar(50),
    job2_end varchar(50),
    job2_title varchar(50),
    job2_description varchar(500),
    job2_company_name varchar(50),
    job3_skills varchar(500),
    job3_start varchar(50),
    job3_end varchar(50),
    job3_title varchar(50),
    job3_description varchar(500),
    job3_company_name varchar(50),
    education varchar(1000),
    ed_highest_level varchar(100),
    school1_name varchar(100),
    school1_grad_date varchar(50),
    school1_major varchar(50),
    school2_name varchar(100),
    school2_grad_date varchar(50),
    school2_major varchar(50),
    skill1_name varchar(50),
    skill2_name varchar(50),
    skill3_name varchar(50),
    skill4_name varchar(50),
    skill5_name varchar(50),
    reference1_name varchar(50),
    reference1_number varchar(15),
    reference1_email varchar(50),
    reference1_relationship varchar(100),
    reference2_name varchar(50),
    reference2_number varchar(15),
    reference2_email varchar(50),
    reference2_relationship varchar(100),
    reference3_name varchar(50),
    reference3_number varchar(15),
    reference3_email varchar(50),
    reference3_relationship varchar(100),
    project1_name varchar(50),
    project1_info varchar(500),
    project1_url varchar(500),
    project2_name varchar(50),
    project2_info varchar(500),
    project2_url varchar(500),
    project3_name varchar(50),
    project3_info varchar(500),
    project3_url varchar(500),
    qr_url varchar(500),
    PRIMARY KEY (id)
);