module.exports = function(sequelize, DataTypes) {
  var User_Data = sequelize.define("User_Data", {
    user_name: {
        type: DataTypes.STRING
    },
    user_email: DataTypes.STRING(64),
    picture_url: DataTypes.STRING,
    first_name: DataTypes.STRING(64),
    last_name: DataTypes.STRING(64),
    phone_number: DataTypes.STRING(16),
    user_address: DataTypes.STRING(64),
    linkedin: DataTypes.STRING,
    github: DataTypes.STRING,
    about: DataTypes.STRING(768),
    quote: DataTypes.STRING,
    job_skills_1: DataTypes.STRING,
    job_start_1: DataTypes.STRING(16),
    job_end_1: DataTypes.STRING(16),
    job_title_1: DataTypes.STRING(64),
    job_description_1: DataTypes.STRING,
    job_company_name_1: DataTypes.STRING(64),
    job_skills_2: DataTypes.STRING,
    job_start_2: DataTypes.STRING(16),
    job_end_2: DataTypes.STRING(16),
    job_title_2:DataTypes.STRING,
    job_description_2: DataTypes.STRING,
    job_company_name_2: DataTypes.STRING(64),
    job_skills_3: DataTypes.STRING,
    job_start_3: DataTypes.STRING(16),
    job_end_3: DataTypes.STRING(16),
    job_title_3: DataTypes.STRING,
    job_description_3: DataTypes.STRING,
    job_company_name_3: DataTypes.STRING(64),
    education: DataTypes.STRING,
    edu_highest_grade: DataTypes.STRING,
    school_name_1: DataTypes.STRING(64),
    school_grad_date_1: DataTypes.STRING(16),
    school_major_1: DataTypes.STRING(64),
    school_about_1: DataTypes.STRING,
    school_name_2: DataTypes.STRING(64),
    school_grad_date_2: DataTypes.STRING(16),
    school_major_2: DataTypes.STRING(64),
    school_about_2: DataTypes.STRING,
    skill_1: DataTypes.STRING(32),
    skill_2: DataTypes.STRING(32),
    skill_3: DataTypes.STRING(32),
    skill_4: DataTypes.STRING(32), 
    skill_5: DataTypes.STRING(32),
    reference_name_1: DataTypes.STRING(64),
    reference_number_1: DataTypes.STRING(16),
    reference_email_1: DataTypes.STRING(64),
    reference_relationship_1: DataTypes.STRING,
    reference_name_2: DataTypes.STRING(64),
    reference_number_2: DataTypes.STRING(16),
    reference_email_2: DataTypes.STRING(64),
    reference_relationship_2: DataTypes.STRING,
    reference_name_3: DataTypes.STRING(64),
    reference_number_3: DataTypes.STRING(16),
    reference_email_3: DataTypes.STRING(64),
    reference_relationship_3: DataTypes.STRING,
    project_name_1: DataTypes.STRING(64),
    project_info_1: DataTypes.STRING,
    project_url_1: DataTypes.STRING,
    project_img_url_1: DataTypes.STRING,
    project_name_2: DataTypes.STRING(64),
    project_info_2: DataTypes.STRING,
    project_url_2: DataTypes.STRING,
    project_img_url_2: DataTypes.STRING,
    project_name_3: DataTypes.STRING(64),
    project_info_3: DataTypes.STRING,
    project_url_3: DataTypes.STRING,
    project_img_url_3: DataTypes.STRING,
    qr_url: DataTypes.STRING,
    key: DataTypes.STRING(256)
    
  });
  return User_Data;
};
